version: '3.8'
services:
  database:
    image: postgres:15
    container_name: chucknorris_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: laravel
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  # api:
  #   build:
  #     context: .
  #   container_name: chucknorris_api
  #   ports:
  #     - "5000:5000"
  #   depends_on:
  #     - database
  #   environment:
  #     - ConnectionStrings__DefaultConnection=Host=database;Database=chucknorris;Username=admin;Password=admin

volumes:
  db_data:
